services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=123qweasd
      - DB_NAME=todo_db
      - DB_PORT=5432
      - JWT_SIGNATURE_KEY=secret

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123qweasd
    volumes:
      - todo_db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  todo_db_data:
